openapi: 3.2.0
info:
  title: Shiprocket Products API
  version: v1
  description: 'Shiprocket''s public REST API (v1/external) for eCommerce shipping and order management: authentication, order create/update/cancel/import, courier serviceability and AWB assignment, pickup scheduling, labels/manifests/invoices, shipment tracking, NDR actions, returns and exchanges, hyperlocal and international shipping, products, listings, channels, inventory, countries/postcodes, wallet balance, statements and discrepancies.'
  termsOfService: https://www.shiprocket.in/terms-conditions/
  contact:
    name: Shiprocket API integration support
    email: integration@shiprocket.com
    url: https://apidocs.shiprocket.in/
servers:
- url: https://apiv2.shiprocket.in
  description: Production
security:
- bearerAuth: []
tags:
- name: Products
  description: Use these APIs to get information on your added products or update their details. You can also add a new product or import them in bulk.
paths:
  /v1/external/products:
    get:
      summary: Get All Products
      description: 'This API can be used to display a detailed list of all the products that you have in your Shiprocket account.

        There are no required parameters to access this API. However, the displayed result can be filtered or sorted using additional parameters.

        Parameters:'
      operationId: getAllProducts
      tags:
      - Products
      parameters:
      - name: page
        in: query
        schema:
          type: integer
        description: The page number you want to display.
      - name: per_page
        in: query
        schema:
          type: integer
        description: The number of products to get per page.
      - name: sort
        in: query
        schema:
          type: string
        description: 'The order to sort by. Value: ASC or DESC'
      - name: sort_by
        in: query
        schema:
          type: string
        description: Allows you to choose the value field by which the items will be sorted. Could be sorted by id, by sku, time created etc.
      - name: filter
        in: query
        schema:
          type: string
        description: The data to be matched for the filter value.
      - name: filter_by
        in: query
        schema:
          type: string
        description: The filter value field . Can be id, sku, etc.
      responses:
        '200':
          description: Successful Call
          content:
            application/json:
              examples:
                Successful-Call:
                  value:
                    data:
                    - id: 17484610
                      sku: chakra123
                      hsn: '441122'
                      name: Kunai
                      description: ''
                      category_code: default
                      category_name: Default Category
                      category_tax_code: ''
                      image: ''
                      weight: 0 kg
                      size: ''
                      cost_price: '0.00'
                      mrp: '0.00'
                      tax_code: default
                      low_stock: 0
                      ean: ''
                      upc: ''
                      isbn: ''
                      created_at: 31 Jul 2019 12:37 PM
                      updated_at: 31 Jul 2019 03:18 PM
                      quantity: 41
                      color: ''
                      brand: ''
                      dimensions: 10 x 10 x 10 cm
                      status: INACTIVE
                      type: Single
                    - id: 9741478
                      sku: LNO7K1670
                      hsn: ''
                      name: hehehprod
                      description: ''
                      category_code: default
                      category_name: Default Category
                      category_tax_code: ''
                      image: ''
                      weight: 0.5 kg
                      size: ''
                      cost_price: '0.00'
                      mrp: '0.00'
                      tax_code: default
                      low_stock: 0
                      ean: ''
                      upc: ''
                      isbn: ''
                      created_at: 22 Apr 2019 12:48 PM
                      updated_at: 22 Apr 2019 12:48 PM
                      quantity: 0
                      color: ''
                      brand: ''
                      dimensions: 10 x 10 x 10 cm
                      status: INACTIVE
                      type: Single
                    meta:
                      pagination:
                        total: 12080
                        count: 15
                        per_page: 15
                        current_page: 1
                        total_pages: 806
                        links:
                          next: https://apiv2.shiprocket.in/v1/external/products?page=2
                Invalid-Data:
                  value:
                    data: []
                    meta:
                      pagination:
                        total: 0
                        count: 0
                        per_page: 15
                        current_page: 3
                        total_pages: 1
                        links:
                          previous: https://apiv2.shiprocket.in/v1/external/products?page=2
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        sku:
                          type: string
                        hsn:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        category_code:
                          type: string
                        category_name:
                          type: string
                        category_tax_code:
                          type: string
                        image:
                          type: string
                        weight:
                          type: string
                        size:
                          type: string
                        cost_price:
                          type: string
                        mrp:
                          type: string
                        tax_code:
                          type: string
                        low_stock:
                          type: integer
                        ean:
                          type: string
                        upc:
                          type: string
                        isbn:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        quantity:
                          type: integer
                        color:
                          type: string
                        brand:
                          type: string
                        dimensions:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                  meta:
                    type: object
                    properties:
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                          count:
                            type: integer
                          per_page:
                            type: integer
                          current_page:
                            type: integer
                          total_pages:
                            type: integer
                          links:
                            type: object
                            properties:
                              next:
                                type: string
    post:
      summary: Add New Products
      description: 'Use this API to add a new product to your Shiprocket account. Provide the required product details and any additional info to successfully add a new product to your product list.

        Notes:

        ''sku'' Id has to be unique. It cannot be the same as an existing sku.

        In case no category code is added, the code should be default.

        ''type'' field should be either ''single'' or ''multiple.''

        Parameters:'
      operationId: addNewProducts
      tags:
      - Products
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            example: "{\n\t \"name\": \"Batman451\",\n    \"category_code\": \"default\",\n    \"type\": \"Single\",\n    \"qty\": \"10\",\n    \"sku\": \"b118771212\",\n    \"qc_details\": {\n        \"product_image\": \"https://kr-multichannel-stage.s3.ap-south-1.amazonaws.com/1310/qc_product_img/538c2939-24e7-4b60-98cd-b13cee264c1e.jpg\",\n        \"brand\": \"redlabel\",\n        \"color\": \"white\",\n        \"size\": \"L\",\n        \"product_imei\": \"\",\n        \"serial_no\": \"790878\",\n        \"ean_barcode\": \"\",\n        \"check_damaged_product\": true\n}"
      responses:
        '201':
          description: Successful Call
        '422':
          description: Missing Fields
          content:
            application/json:
              examples:
                Missing-Fields:
                  value:
                    message: There were errors in adding new product!
                    errors:
                      sku:
                      - The sku field is required.
                    status_code: 422
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      sku:
                        type: array
                        items:
                          type: string
                  status_code:
                    type: integer
  /v1/external/products/show/{product_id}:
    get:
      summary: Get Specific Product Details
      description: 'Use this API to get the details of a specific product. The product details will be displayed in JSON format.

        You need to pass the product id in the endpoint URL for the successful call of the API. No other body parameters are required.

        Path:'
      operationId: getSpecificProductDetails
      tags:
      - Products
      parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful Call
          content:
            application/json:
              examples:
                Successful-Call:
                  value:
                    data:
                      id: 17484610
                      sku: chakra123
                      name: Kunai
                      description: ''
                      category_code: ''
                      category_name: ''
                      category_tax_code: ''
                      image: ''
                      weight: '0.000'
                      size: ''
                      cost_price: '0.00'
                      mrp: '0.00'
                      tax_code: ''
                      low_stock: 0
                      ean: ''
                      upc: ''
                      isbn: ''
                      created_at: 31 Jul 2019 12:37 PM
                      updated_at: 31 Jul 2019 03:18 PM
                      quantity: 41
                      color: ''
                      brand: ''
                      dimensions: 0.00 x 0.00 x 0.00
                      status: INACTIVE
                      is_combo: 0
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      sku:
                        type: string
                      name:
                        type: string
                      description:
                        type: string
                      category_code:
                        type: string
                      category_name:
                        type: string
                      category_tax_code:
                        type: string
                      image:
                        type: string
                      weight:
                        type: string
                      size:
                        type: string
                      cost_price:
                        type: string
                      mrp:
                        type: string
                      tax_code:
                        type: string
                      low_stock:
                        type: integer
                      ean:
                        type: string
                      upc:
                        type: string
                      isbn:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      quantity:
                        type: integer
                      color:
                        type: string
                      brand:
                        type: string
                      dimensions:
                        type: string
                      status:
                        type: string
                      is_combo:
                        type: integer
        '400':
          description: Invalid Data
          content:
            application/json:
              examples:
                Invalid-Data:
                  value:
                    message: This product is either inactive or does not exist
                    status_code: 400
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
        '404':
          description: Missing Fields
          content:
            application/json:
              examples:
                Missing-Fields:
                  value:
                    message: 404 Not Found
                    status_code: 404
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
  /v1/external/products/qc-product-update/{productID}:
    post:
      summary: Convert to QC Product
      description: 'Use this API to convert an existing product to a QC product. The {productID} will be the "id" from the " Get all products " or " Get specific product details " API.

        Parameters:'
      operationId: convertToQCProduct
      tags:
      - Products
      parameters:
      - name: productID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sku:
                  type: string
                  description: Stock Keeping Unit or the identification unit of an individual product (generally alphanumeric).
                product_image:
                  type: string
                  description: Pickup agent will cross check shared product color with the actual product received from the buyer. Mandatory for all QC Products
                brand_box:
                  type: string
                  description: The pickup agent will cross-check the provided brand name, which should match the brand tag affixed to the item(s) upon delivery
                brand:
                  type: integer
                  description: The pickup agent will cross-check the provided brand name visible on the item(s) or its packaging.
                color:
                  type: string
                  description: Pickup agent will cross check shared product color with the actual product received from the buyer.
                size:
                  type: string
                  description: Pickup agent will cross check shared product size with the size on the label/tag.
                serial_no:
                  type: string
                  description: A serial number (SN) is a unique alphanumeric value assigned to each individual product.
                check_damaged_product:
                  type: integer
              required:
              - sku
              - product_image
            example:
              sku: PROD12345
              product_image: https://kr-multichannel.s3.ap-southeast-1.amazonaws.com/2/products/images/1640350781_08d63a46-a0f1-4d6b-9eea-9e476fce7c4e1575377853407-HIGHLANDER-by-Rohit-Sharma-Men-White--Blue-Slim-Fit-Checked--1.j
              brand_box: 12323chacha
              brand: blue
              color: Red
              size: M
              serial_no: ''
              check_damaged_product: 0
      responses:
        '200':
          description: Success (no example response published in the collection)
  /v1/external/products/import:
    post:
      summary: Bulk Import Products
      description: Use this API to import your products in bulk from a .csv file. No parameters are required. Choose the target file as required. You will receive an import id upon successful import operation.
      operationId: bulkImportProducts
      tags:
      - Products
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful Call
          content:
            application/json:
              examples:
                Successful-Call:
                  value:
                    id: 20290943
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '422':
          description: Missing Fields
          content:
            application/json:
              examples:
                Missing-Fields:
                  value:
                    message: Oops! Something went wrong.
                    errors:
                      file:
                      - The file field is required.
                    status_code: 422
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      file:
                        type: array
                        items:
                          type: string
                  status_code:
                    type: integer
  /v1/external/products/sample:
    get:
      summary: Get Sample .csv Format
      description: 'This API will provide a sample format for a CSV file that can be used for importing orders. You can use this format to create your CSV file, which you want to use to import products into your Shiprocket account.

        No additional parameters are required.'
      operationId: getSampleCsvFormat
      tags:
      - Products
      responses:
        '200':
          description: Successful Call
          content:
            application/csv:
              examples:
                Successful-Call:
                  value: '"Category Name","*Master Sku Code","*Product Name","Low Stock Warning At","Description","Length (cm)","Width (cm)","Height (cm)","Weight (kgs)","ean","upc","isbn","Color","Brand","Size","Tax Code","Image Url","Custom Detail Fields (IMEI/SerialNumber)","MRP","Cost Price","Active(True/False)","Type(Single)","HSN code"

                    "Below given is the sample data. Please delete the same and create/upload data as per you requirements. ","","","","","","","","","","","","","","","","","","","","","",""

                    "Default","Tshirt-Blue-42","Blue tshirt 42 size","2","blue polo tshirt with round collor large size","50","42","","500","1235467891111","","","blue","nike","42","5","http://www.onlinebachat.com/photos/MjAxNi0wMy0yMCAwNzowMzo1Nw==_tshirt%20yellow.jpg","","2500","1500","","",""

                    "Electronics","Iphone5s","Iphone5s","1","iphone 5s with 1 year warranty...","","","","","","","","Black","Iphone","","","","IMEI","20000","","","",""

                    "Electronics","Iphone6","Iphone6","1","iphone 6 with 1 year manufacturer warranty..","","","","","","","","Silver","Iphone","","","","IMEI","50000","","True","",""

                    '
        '404':
          description: Wrong Endpoint
          content:
            application/json:
              examples:
                Wrong-Endpoint:
                  value:
                    message: 404 Not Found
                    status_code: 404
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT obtained from POST /v1/external/auth/login using an API user email + password (Settings > API > Add New API User). The token is valid for 10 days; send it as Authorization: Bearer <token>.'
externalDocs:
  url: https://apidocs.shiprocket.in/
  description: Shiprocket API documentation (Postman documenter)
x-generated-from:
  type: postman-collection
  url: https://apidocs.shiprocket.in/api/collections/8407119/SzYW1zB2?environment=8407119-3ebd70ec-0118-4aa7-a886-4802616014f5&segregateAuth=true&versionTag=latest
  documenter: https://apidocs.shiprocket.in/
  collection_id: f5af337c-69fc-49c7-8418-e2f6ee461674
  generated: '2026-09-18'
  method: generated
  note: Faithful conversion; schemas inferred from published parameter tables and examples.
